#!/usr/bin/env python

from sys     import argv, stdin
from couchdb import Server
from base64  import b64encode

s  = Server()
db = s['hindsight']

key  = argv[1]
data = b64encode(file('/dev/stdin', 'rb').read())

try:
    db.save({'_id': key, 'data': data})
except Exception as e:
    doc = db.get(key)
    if doc is None:
        raise e
    doc['data'] = data
    db.update([doc])

db.commit()
